name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.26.x', '1.27.x']
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@v7.0.0
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - run: go build ./...
      - run: go test -race ./...
      - run: go vet ./...
